# Generated by Django 5.1.6 on 2025-02-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
